/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Forms;

import Entities.Categorie;
import Service.CategorieService;
import java.io.FileOutputStream;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hasna
 */
public class CategorieForm extends javax.swing.JInternalFrame {

      private CategorieService Cat=new CategorieService();
      private DefaultTableModel model;
      private static int id;
    /**
     * Creates new form CategorieForm
     */
    public CategorieForm() {
        initComponents();
        this.setTitle("Gestions des Chambres");
        
        model=(DefaultTableModel) ListeCategories.getModel();
        load();
        }
        private void load(){
            CategorieService Cat = new CategorieService();

        List<Categorie> categories = Cat.findAll();

        DefaultTableModel model = (DefaultTableModel) ListeCategories.getModel();
            model.setRowCount(0);
            for(Categorie cat : Cat.findAll()){
                model.addRow(new Object[]{
                    cat.getId(),
                    cat.getCode(),
                    cat.getLibelle(),
                    });
               System.out.println(cat.getId());
         }
         }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        code = new javax.swing.JTextField();
        libelle = new javax.swing.JTextField();
        supprimer = new javax.swing.JButton();
        addCategorie = new javax.swing.JButton();
        modifier = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListeCategories = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 153, 153));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(725, 831));

        jLabel1.setFont(new java.awt.Font("Khmer MN", 1, 48)); // NOI18N
        jLabel1.setText("Gestion des Categories");

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel2.setText("Code");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel3.setText("Libelle");

        code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codeActionPerformed(evt);
            }
        });

        supprimer.setBackground(new java.awt.Color(255, 102, 102));
        supprimer.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        supprimer.setText("Supprimer");
        supprimer.setPreferredSize(new java.awt.Dimension(94, 31));
        supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerActionPerformed(evt);
            }
        });

        addCategorie.setBackground(new java.awt.Color(0, 153, 0));
        addCategorie.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        addCategorie.setText("Enregistrer");
        addCategorie.setPreferredSize(new java.awt.Dimension(98, 31));
        addCategorie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCategorieActionPerformed(evt);
            }
        });

        modifier.setBackground(new java.awt.Color(255, 153, 51));
        modifier.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        modifier.setText("Modifier");
        modifier.setPreferredSize(new java.awt.Dimension(90, 31));
        modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(supprimer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(libelle)
                            .addComponent(code))))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(libelle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(supprimer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        ListeCategories.setBackground(new java.awt.Color(204, 204, 255));
        ListeCategories.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ListeCategories.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "id", "Code", "Libelle"
            }
        ));
        ListeCategories.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListeCategoriesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ListeCategories);

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel4.setText("Liste Categories");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cat.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel1)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addCategorieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCategorieActionPerformed
if(       Cat.create(new Categorie(code.getText(),libelle.getText()))) {
  //  System.out.println(" code: "+ code.getText()+" libelle"+libelle.getText());
    
} else
{
    System.out.println(" Great ");
}
    JOptionPane.showMessageDialog(this,"Categorie Bien Créée");    
    load();    }//GEN-LAST:event_addCategorieActionPerformed

    
    private void supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerActionPerformed
            System.out.println("Attempting to delete Category with ID: " + id);

    int reponse = JOptionPane.showConfirmDialog(this, "Voulez-vous vraiment supprimer ce categorie?");
    if (reponse == 0) {
        Categorie categorieToDelete = Cat.findById(id);
        if (categorieToDelete == null) {
            JOptionPane.showMessageDialog(this, "Categorie non trouvée !");
            return;
        }

        // Try to delete the category
        boolean success = Cat.delete(categorieToDelete);
        if (success) {
            JOptionPane.showMessageDialog(this, "Categorie Bien Supprimé");
        } else {
            JOptionPane.showMessageDialog(this, "Erreur lors de la suppression de la catégorie");
        }
    }
    load();
    }//GEN-LAST:event_supprimerActionPerformed

    private void codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeActionPerformed
        
    }//GEN-LAST:event_codeActionPerformed

    private void modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierActionPerformed
       
        String Code = code.getText();
        String Libelle = libelle.getText();
    
        Categorie ct = Cat.findById(id);
        if (ct == null) {
            JOptionPane.showMessageDialog(this, "Categorie introuvable !");
            return; // Arrêter l'exécution si le client est introuvable
        }

        ct.setCode(Code);
        ct.setLibelle(Libelle);


         int reponse = JOptionPane.showConfirmDialog(this, "Voulez-vous vraiment modifier ce categorie ?");
        if (reponse == 0) {
            if (Cat.update(ct)) {
                JOptionPane.showMessageDialog(this, "Categorie Bien Modifié");
            } else {
                JOptionPane.showMessageDialog(this, "Erreur lors de la modification du categorie");
            }
        }
        load();
    }//GEN-LAST:event_modifierActionPerformed

    private void ListeCategoriesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListeCategoriesMouseClicked
         int row = ListeCategories.getSelectedRow(); // Get the selected row
    if (row >= 0) {
        id = Integer.parseInt(ListeCategories.getValueAt(row, 0).toString()); // Capture category ID
        code.setText(ListeCategories.getValueAt(row, 1).toString()); // Set 'Code' field
        libelle.setText(ListeCategories.getValueAt(row, 2).toString()); // Set 'Libelle' field
    }
    }//GEN-LAST:event_ListeCategoriesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ListeCategories;
    private javax.swing.JButton addCategorie;
    private javax.swing.JTextField code;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField libelle;
    private javax.swing.JButton modifier;
    private javax.swing.JButton supprimer;
    // End of variables declaration//GEN-END:variables
}
