/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package Forms;

import Forms.ChambreDates;

/**
 *
 * @author hasna
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem1 = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Khmer MN", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 255));
        jLabel1.setText("LUXURY HOTEL");
        desktopPane.add(jLabel1);
        jLabel1.setBounds(460, 160, 360, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel.png"))); // NOI18N
        desktopPane.add(jLabel2);
        jLabel2.setBounds(-10, -20, 500, 400);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("InaiMathi", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 255));
        jLabel3.setText("L'alliance parfaite entre élégance ");
        desktopPane.add(jLabel3);
        jLabel3.setBounds(500, 240, 270, 30);

        jLabel4.setFont(new java.awt.Font("InaiMathi", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 255));
        jLabel4.setText("et confort, pour une expérience unique. ");
        desktopPane.add(jLabel4);
        jLabel4.setBounds(500, 280, 310, 24);

        fileMenu.setBackground(new java.awt.Color(204, 204, 255));
        fileMenu.setMnemonic('f');
        fileMenu.setText("Gestion");

        openMenuItem.setBackground(new java.awt.Color(51, 51, 51));
        openMenuItem.setFont(new java.awt.Font("Helvetica Neue", 3, 24)); // NOI18N
        openMenuItem.setForeground(new java.awt.Color(51, 51, 255));
        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Clients");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(openMenuItem);

        saveMenuItem.setBackground(new java.awt.Color(51, 51, 51));
        saveMenuItem.setFont(new java.awt.Font("Helvetica Neue", 3, 24)); // NOI18N
        saveMenuItem.setForeground(new java.awt.Color(51, 51, 255));
        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Chambres");
        saveMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setBackground(new java.awt.Color(51, 51, 51));
        saveAsMenuItem.setFont(new java.awt.Font("Helvetica Neue", 3, 24)); // NOI18N
        saveAsMenuItem.setForeground(new java.awt.Color(51, 51, 255));
        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Categories");
        saveAsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAsMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(saveAsMenuItem);

        saveAsMenuItem1.setBackground(new java.awt.Color(51, 51, 51));
        saveAsMenuItem1.setFont(new java.awt.Font("Helvetica Neue", 3, 24)); // NOI18N
        saveAsMenuItem1.setForeground(new java.awt.Color(51, 51, 255));
        saveAsMenuItem1.setMnemonic('a');
        saveAsMenuItem1.setText("Reservation");
        saveAsMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAsMenuItem1ActionPerformed(evt);
            }
        });
        fileMenu.add(saveAsMenuItem1);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Recherche");

        cutMenuItem.setBackground(new java.awt.Color(0, 0, 0));
        cutMenuItem.setFont(new java.awt.Font("Helvetica Neue", 3, 24)); // NOI18N
        cutMenuItem.setForeground(new java.awt.Color(51, 51, 255));
        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("FindChambreByCategorie");
        cutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(cutMenuItem);

        copyMenuItem.setBackground(new java.awt.Color(0, 0, 0));
        copyMenuItem.setFont(new java.awt.Font("Helvetica Neue", 3, 24)); // NOI18N
        copyMenuItem.setForeground(new java.awt.Color(51, 51, 255));
        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("findChambreBetweenDates ");
        copyMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(copyMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Dashboard");

        aboutMenuItem.setBackground(new java.awt.Color(0, 0, 0));
        aboutMenuItem.setFont(new java.awt.Font("Helvetica Neue", 3, 24)); // NOI18N
        aboutMenuItem.setForeground(new java.awt.Color(51, 51, 255));
        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("Home");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 818, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
        ClientForm Cf = new ClientForm();
            desktopPane.add(Cf);
         Cf.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_openMenuItemActionPerformed

    private void saveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItemActionPerformed
        ChambreForm Cbs = new ChambreForm();
            desktopPane.add(Cbs);
         Cbs.setVisible(true);    }//GEN-LAST:event_saveMenuItemActionPerformed

    private void saveAsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAsMenuItemActionPerformed
        CategorieForm Cat = new CategorieForm();
            desktopPane.add(Cat);
         Cat.setVisible(true);
    }//GEN-LAST:event_saveAsMenuItemActionPerformed

    private void saveAsMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAsMenuItem1ActionPerformed
          ReservationForm Reserve = new ReservationForm();
            desktopPane.add(Reserve);
            Reserve.setVisible(true);
        
    }//GEN-LAST:event_saveAsMenuItem1ActionPerformed

    private void cutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutMenuItemActionPerformed
        ChambreByCategorie chmcat = new ChambreByCategorie();
        desktopPane.add(chmcat);
        chmcat.setVisible(true);
    }//GEN-LAST:event_cutMenuItemActionPerformed

    private void copyMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyMenuItemActionPerformed
        ChambreDates chmdte = new ChambreDates();
        desktopPane.add(chmdte);
        chmdte.setVisible(true);
    }//GEN-LAST:event_copyMenuItemActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
         DashboardForm dash = new DashboardForm();
        desktopPane.add(dash);
        dash.setVisible(true);
                              
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem1;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables

}
